services:
  - type: web
    name: kinobot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: BOT_TOKEN
        sync: false
      - key: ADMINS
        sync: false
      - key: CHANNELS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: kinobot-db
          property: connectionString
    databases:
      - name: kinobot-db
        databaseName: kinobot
        user: kinobot
